### ISSUE TITLE
Feature request: Add getter for connection status

### ISSUE THREAD

**Issue by dsbaars** [riccardobl/nostrduino#2]
I've looking into the code, but I couldn't find a way to check connection status.
I would like to be able to see whether there is connection to at least one relay and preferably also able to subscribe to connect and disconnect events. 

It might be sufficient to just expose `ws` from ESP32Connection which is now private?

**Comment by riccardobl** [comment]
I'd rather avoid exposing ws so that the code using this library is not tied to a specific websocket library, but i can expose wrappers to the functionalities we find to be useful.

I've added a way to add listeners to connection events, and a method to get the list of connected NostrRelays, from which you can get their Connection object and url.

Check the example here:
https://github.com/riccardobl/nostrduino/blob/74c2e870b4f25155ddc51ca420a6b1f82ac2dee5/examples/ESP32TestNip01Filter/ESP32TestNip01Filter.cpp#L90-L104

Please let me know if this covers your usecase.

**Comment by dsbaars** [comment]
Yes, great work. Thanks again!
